# Generated by Django 4.1.5 on 2023-01-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_siswa_asal_sekolah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='asal_sekolah',
        ),
    ]
